### ISSUE TITLE
Where to get Lidar?

### ISSUE THREAD

**Issue by akhilesh-k** [iliasam/OpenSimpleLidar#1]
This isn't exactly an issue, but I was curious from where to buy this lidar module. I coudn't find any single place where lidar is being sold at this price.
It would be great if you can help with using hardware modules.

**Comment by iliasam** [comment]
It does not sold - there is no production on this Lidars.
> it's **components** cost less than $35.

**Comment by akhilesh-k** [comment]
Hello iliasam,
Many thanks for replying.
I want to explore in fields of self driving cars so this is important for me. Can you suggest how to reproduce such a laser rangefinder with minimum cost.


Regards,


Akhilesh Kumar

Sophomore,

Major: Electronics and Communication Engineering
Jaypee University of Information Technology, Waknaghat



mail: akhilesh_k@outlook.com

https://akhilesh-k.github.io

________________________________
