### ISSUE TITLE
Likely problem with R102 

### ISSUE THREAD

**Issue by HaroldSapientia** [iliasam/OpenSimpleLidar#11]
In the BOM, R102 is 10k. But in the pcb design file it's 1k. What exactly it should be?

**Comment by iliasam** [comment]
It must be 10k, thanks for feedback!

**Comment by iliasam** [comment]
Sorry, I'm mistaken, it should be 1k as at the schematic.
I had updated all BOMs.

**Comment by HaroldSapientia** [comment]
An additional problem, I'm a freshman. What does 240 ohms (adj) for R100 mean? Thank you！

**Comment by iliasam** [comment]
This resistor is limiting current of encoder LED. 
I had updated the schematic: https://github.com/iliasam/OpenSimpleLidar/blob/master/PCB/CommonPCB_v1.2M/Schematic_motor_v1.2.png
