### ISSUE TITLE
Gerbers are not source

### ISSUE THREAD

**Issue by Snowda** [iliasam/OpenSimpleLidar#4]
Currently the PCB files are provided in gerber file format which are only used as input for manufacturing. These are generated output, not actual reasonably easy to modify _original_ source files. If I want to go round off some corners (for example) it's really not worth the sheer amount of effort that would be needed to modify them. 

Native Eagle, Altium, KiCad, etc. files would be much easier to access. Until that happens, I wouldn't be exactly referring to this as "open".

**Comment by iliasam** [comment]
OK, I will add project files soon.

**Comment by iliasam** [comment]
I have added project files for the "CommonPCB".
