### ISSUE TITLE
CPL file?

### ISSUE THREAD

**Issue by ajsnyde** [iliasam/OpenSimpleLidar#8]
Sorry, noob question. Not sure what I should give for a CPL file when ordering through jlcpcb:
![image](https://user-images.githubusercontent.com/11302823/227806701-95adfa2f-14b5-436f-b662-38b3e1b6a05a.png)

**Comment by iliasam** [comment]
This project is not designed for assembling at the factory, and I don't have files for that.
Also this PCB has components at both sides, while JLCPCB can install components only at the one side.

**Comment by ajsnyde** [comment]
Ah! Ok, that makes sense! I'll order and assemble it myself. Saw they had a promotion for free assembly and thought that was the "right" way to do it. Thanks man!
